---
title: "Class 4 - R Data Frames"
output: 
  html_document:
    toc: true 
    toc_float: true
    number_sections: true
    code_folding: show
    code_download: true
date: "2026-09-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Frames
```{r df}
crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")

crashes_df = tibble::tibble(
  day     = names(crashes_by_day),
  crashes = crashes_by_day,
  busy    = crashes_by_day > 2000
)
crashes_df

dplyr::glimpse(crashes_df)  # dpylyr is the package name, glimpse is the function
                            # Equivalent to str() but in a neater format
```

```{r list}
# a list is more flexible than a vector. It can hold any arrangement of data types
example_list = list(
  1:3,                    # integers 1, 2, 3
  "a",                    # one piece of text
  c(TRUE, FALSE, TRUE),   # three logicals
  c(2.3, 5.9)             # two decimals
)
str(example_list)         # the x-ray view

str(example_list[1])     # [ ]  the shaker: a list of 1
str(example_list[[1]])   # [[ ]] the packet: the element
example_list[[1]][[1]]   # the pepper: first value in it
example_list[[4]][2]     # element 4, then its 2nd value

```

# Examing the job add
```{r job_add}
job = list(
  title   = "Research Data Scientist, Magic Eye",
  company = "Google",
  salary  = list(min = 147000, max = 210000)
)
str(job)

# $ is for finding names elements in a list
# Write one expression to extract each of

# 1. The company name.
company_name = job$company # or job[[2]] however this returns a list of job[2]
company_name
job[[2]] 
# 2. The maximum salary.
max_salary = job$salary$max 
max_salary
# 3. The maximum salary again, using only [[ ]].
max_salary = job[[3]][[2]] # -> the 2nd item in the 3rd item of job list
max_salary
# 4. The names of the elements in job.
names(job)

```

# Subsetting a Vector
```{r vector_subset}
# Cannot use a dolar sign with a vector -> use brackets

# Will both return the same thing
crashes_by_day[2]
crashes_by_day["Tue"]

# Can subset by condition
crashes_by_day[crashes_by_day > 2300]

# can subset by range -> inclusive
crashes_by_day[2:4]

# Can pass a vector to subset a vector, same as above subset
crashes_by_day[c("Tue", "Wed", "Thu")]

```

# Subsetting a data frame
```{r dataframe_subset}
crashes_df = tibble::tibble(
  day     = names(crashes_by_day),
  crashes = crashes_by_day,
  busy    = crashes_by_day > 2000)
crashes_df$crashes                     # one column, as a vector

crashes_df[["crashes"]]                # the same vector, by name

crashes_df[1:2, c("day", "crashes")]   # rows 1 to 2, two columns
                                       # [1:2] refers to Mon/Tue rows, day and crashes are the columns from those rows

```


# Ohio Jobs
```{r jobs_csv}
oh_jobs = readr::read_csv(
  file = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=IHLIDXUSOH&scale=left&cosd=2021-08-28&coed=2026-08-28&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Daily%2C%207-Day&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-09-02&revision_date=2026-09-02&nd=2020-02-01"
)
dplyr::glimpse(oh_jobs)

oh_jobs_base_r = read.csv("https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=IHLIDXUSOH&scale=left&cosd=2021-08-28&coed=2026-08-28&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Daily%2C%207-Day&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-09-02&revision_date=2026-09-02&nd=2020-02-01")

dplyr::glimpse(oh_jobs_base_r)

```




