---
title: "Class 8"
output: 
  html_document:
    toc: true 
    toc_float: true
    number_sections: true
    code_folding: show
    code_download: true
date: "2026-09-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r API_Setup_Cincy_Crashes}
httr2::request("https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json") |>
  httr2::req_url_query("$limit" = 5) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> cincy_crashes

cincy_crashes
```

```{r FRED_API}
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json"
  ) |>
  # nothing has been sent yet
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> results

jobs_df = results$observations



# post processing on the data to find September dates
jobs_df |> 
  dplyr::mutate(
    date = lubridate::ymd(date)
  ) |> 
  dplyr::filter(date >= '2026-09-01') -> jobs_df_modified



# other option is to use the API since it has observation_start
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json",
    observation_start="2026-09-01"
  ) |>
  # nothing has been sent yet
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> ohio_jobs_sep_2026
  
  sep_df = ohio_jobs_sep_2026$observations


```

```{r USA_JOBS_API}
# 1. How many federal postings match "Data Analyst" today?
# 2. Which three departments have the most of them?
httr2::request("https://data.usajobs.gov/api/search") |>
  httr2::req_url_query(Keyword = stringr::str_detect(pattern = "Data*Analy*"), ResultsPerPage = 500) |>
  httr2::req_headers(
    Host = "data.usajobs.gov",
    "User-Agent" = "valeskjw@miamioh.edu",
    "Authorization-Key" = Sys.getenv("USAJOBS_API_KEY")
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = TRUE) -> usa_jobs_result

usa_jobs_df = usa_jobs_result$SearchResult$SearchResultItems

# q1 = 241

departments = usa_jobs_df |> 
  dplyr::group_by(MatchedObjectDescriptor.DepartmentName) |> 
  dplyr::mutate(n = dplyr::n()) |> 
  dplyr::arrange(dplyr::desc(n))



```



