---
title: "Class 11"
output: 
  html_document:
    toc: true 
    toc_float: true
    number_sections: true
    code_folding: show
    code_download: true
date: "2026-10-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Bulletin Example
```{r bulletin}
dept_abbrv = c('acc', 'bus', 'isa', 'mkt')

courses_df = data.frame() # initializing a container to store stuff in from the loop
for (abbrv in dept_abbrv) {
  cat( rep("-", 50) , "\n" )
  print(abbrv)
  bulletin_url = paste0(
    'https://bulletin.miamioh.edu/courses-instruction/', abbrv, '/'
  )
  
  # Q: Why did Fadel make this an R object instead of a string like last class?
  # [a] we did this so we can reuse the rest of our code with only changing the URL
  webpage = rvest::read_html(bulletin_url)
  
  webpage |> rvest::html_elements("strong") |> rvest::html_text2() -> titles
  webpage |> rvest::html_elements("p.courseblockdesc") |> rvest::html_text2() -> descs
  
  df = data.frame(title = titles, desc = descs)
  print(df$title[1:2])
  courses_df = rbind(courses_df, df)
}
```

```{r purr}
dept_abbrv = c('acc', 'bus', 'isa', 'mkt')

# This function takes an abbrv as an input and returns a data_frame as an output
scrape_mu_bulletin = function(abbrv){
  bulletin_url = paste0(
    'https://bulletin.miamioh.edu/courses-instruction/', abbrv, '/'
  )
  
  # Q: Why did Fadel make this an R object instead of a string like last class?
  # [a] we did this so we can reuse the rest of our code with only changing the URL
  webpage = rvest::read_html(bulletin_url)
  
  webpage |> rvest::html_elements("p.courseblocktitle") |> rvest::html_text2() -> titles
  webpage |> rvest::html_elements("p.courseblockdesc") |> rvest::html_text2() -> descs
  
  df = data.frame(title = titles, desc = descs)
  return(df)
}

test = scrape_mu_bulletin(abbrv = 'eco')

# to use functions from purrr, we will use a map_*(), or map2_*(), or a pmap_*()
# map uses a function that takes a single input (or you are only changing a single input)
# map2 uses a function that takes two inputs
# pmap >=3
# after the _, you put the type of object you are getting back

# the .x is the vector that we will iterate over
# and the .f is the function we use

courses_df_from_purrr = purrr::map_df(.x = dept_abbrv, .f = scrape_mu_bulletin)
```

```{r plane_Crash_info}
year = 2025

crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')

crash_page <- rvest::read_html(crash_url, encoding = "ISO-8859-1")

# This should now print without the error
crash_page

crash_tables <- crash_page |>
  rvest::html_elements("table") |>
  rvest::html_table()
```



